# tinyimagenet_lamaml.yaml

data_path: data/rff/rfmls
dataset: iq
cuda: true
log_dir: logs/
log_every: 3125

model: meralg1 #_cifar
expt_name: meralg1_lora_cf_test

memories: 400 #1024
batch_size: 128
replay_batch_size: 64
n_epochs: 10
samples_per_task: 2048
# memory_strength: 0 #0.5

lr: 0.1
beta: 0.1
gamma: 1.0
opt_lr: 0.4
alpha_init: 0.1
opt_wt: 0.1
grad_clip_norm: 10.0 #5.0
glances: 1

loader: task_incremental_loader
increment: 5 # number of classes in every task
arch: resnet1d
cifar_batches: 5

learn_lr: true
second_order: true
class_order: random
seed: 0
calc_test_accuracy: false
validation: 0.1
