# La-MAML specific defaults
model: lamaml_cifar
opt_lr: 0.1 # n
alpha_init: 0.1 # alpha
learn_lr: true
sync_update: false
use_old_task_memory: false
second_order: true
memories: 5120
replay_batch_size: 20
glances: 1
