# La-MAML specific defaults
model: lamaml_cifar
opt_lr: 0.0003 # n
opt_wt: 0.0001 # beta
alpha_init: 0.0003 # alpha
learn_lr: true
sync_update: true
use_old_task_memory: false
second_order: true
memories: 5120
replay_batch_size: 20
glances: 1
